### ISSUE TITLE
Native client doesn't support complex sorting rules

### ISSUE THREAD

**Issue by williamhogman** [clojurewerkz/elastisch#166]
First off, thanks for an awesome library, its a real pleasure to use :+1: . 

Now to my problem, I'm currently working on porting a system using the REST API over to the native one, and I've run into trouble when attempting more complex sorts.

For example using a sort of the form:

```
{"example.updated_at" {:mode "max" :nested_filter {:bool {:must   {:term {"example.user_id" "df0aab05-8ce1-49e4-b7ab-135ed4e641a9"}}
                                                          :should [{:missing {:field "example.list_id"}}
                                                                   {:term {"example.list_id" "b63b3bcc-2292-412d-85d4-036113d29a74"}}]}}
                       :order "desc"}}
```

Results in a stacktrace like this:

```
Caused by: java.lang.ClassCastException: clojure.lang.PersistentHashMap cannot be cast to clojure.lang.Named
	at clojure.core$name.invoke(core.clj:1518)
	at clojurewerkz.elastisch.native.conversion$set_sort.invoke(conversion.clj:574)
	at clojurewerkz.elastisch.native.conversion$__GT_search_request.invoke(conversion.clj:700)
	at clojurewerkz.elastisch.native.document$search_all_types.doInvoke(document.clj:326)
	[...snip...]
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.load(Compiler.java:7130)
```

Happy to provide any other details if necessary :)

**Comment by michaelklishin** [comment]
I'm going to close this:

 * We support `:sort` values that are `SortBuilder`s. While this is not as nice as maps, ElasticSearch allows for really complicated builders and in a dynamically typed language, mapping them to their Java counterparts is really hairy. So using Java interop for those who need it is a better option.
 * Besides nested filters, we support most cases with maps and string-based filters just fine.

**Comment by williamhogman** [comment]
I understand. Thanks for addressing this. 👍
